name: Python application test and coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Adjust this line to use your desired Python version
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run pytest with coverage
      run: |
        pip install coverage
        pip install coveralls
        coverage run -m pytest
        coverage report
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.xml # Ensure your coverage tool generates a coverage report at this location
        flag-name: run-${{ matrix.os }}-py${{ matrix.python-version }}
        parallel: true
        parallel-finished: true
